name: Build and Push Docker Image to Artifactory

on:
  push:
    branches: ['main']

env:
  REGISTRY: solengeu.jfrog.io
  REPO: tasky-docker-local
  IMAGE_NAME: tasky
  IMAGE_TAG: latest
  BUILD_NAME: tasky-build
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          url: ${{ secrets.JFROG_URL }}
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}

      - name: Configure JFrog CLI for docker
        run: |
          jf docker-config --repo-resolve=${{ env.REPO }} --repo-deploy=${{ env.REPO }}

      - name: Build and push image with JFrog CLI
        run: |
          docker build -t $REGISTRY/$REPO/$IMAGE_NAME:$IMAGE_TAG .
          jf docker push $REGISTRY/$REPO/$IMAGE_NAME:$IMAGE_TAG \
            --build-name=${{ env.BUILD_NAME }} \
            --build-number=${{ env.BUILD_NUMBER }}

      - name: Collect environment and Git data
        run: |
          jf rt bce $BUILD_NAME $BUILD_NUMBER
          jf rt bag $BUILD_NAME $BUILD_NUMBER

      - name: Publish Build Info
        run: |
          jf rt bp $BUILD_NAME $BUILD_NUMBER

      - name: Run Xray Scan
        run: |
          jf xr scan --build=$BUILD_NAME/$BUILD_NUMBER \
          --output=json > xray-results.json || true

      - name: Add scan results to GitHub Summary
        run: |
          echo "### Xray Scan Summary" >> $GITHUB_STEP_SUMMARY
          cat xray-results.json | jq -r '.summary | to_entries[] | "- \(.key): \(.value)"' >> $GITHUB_STEP_SUMMARY
